### ISSUE TITLE
Fury 0.5.1 Deserialize Error

### ISSUE THREAD

**Issue by weijiang157152688** [apache/fory#1656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

0.5.1

### Component(s)

Java

### Minimal reproduce step

https://github.com/apache/incubator-fury/pull/1655

### What did you expect to see?

 Deserialize ok

### What did you see instead?

at org.apache.fury.Fury.handleReadFailed(Fury.java:800)
	at org.apache.fury.Fury.deserialize(Fury.java:762)
	at org.apache.fury.Fury.deserialize(Fury.java:680)
	at org.apache.fury.ThreadLocalFury.deserialize(ThreadLocalFury.java:130)
	at org.apache.fury.serializer.DeserializeTest.test(DeserializeTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.AssertionError: 0
	at org.apache.fury.resolver.ClassResolver.getClassInfo(ClassResolver.java:1060)
	at org.apache.fury.resolver.ClassResolver.readClassInfo(ClassResolver.java:1590)
	at org.apache.fury.resolver.FieldResolver.skipObjectField(FieldResolver.java:515)
	at org.apache.fury.resolver.FieldResolver.skipDataBy8(FieldResolver.java:493)
	at org.apache.fury.resolver.FieldResolver.skipEndFields(FieldResolver.java:527)
	at me.ele.lpd.dispatch.matrix.score.common.oss.AssignContextOtherPackageFuryRefCompatibleCodec_1_414493378_355518265.read(AssignContextOtherPackageFuryRefCompatibleCodec_1_414493378_355518265.java:144)
	at org.apache.fury.Fury.readDataInternal(Fury.java:933)
	at org.apache.fury.Fury.readRef(Fury.java:835)
	at org.apache.fury.Fury.deserialize(Fury.java:758)
	... 30 more

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
It fails at :
![image](https://github.com/apache/incubator-fury/assets/12445254/94fff95e-649b-4f52-9ae8-7f93bbba1537)

The serialization and deserialization has different schema, could you share the classdef of your serialization peer?
